# Generated by Django 5.0.1 on 2025-02-01 04:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Bengali answer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Hindi answer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_bn",
            field=models.TextField(
                blank=True, help_text="Bengali translation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(
                blank=True, help_text="Hindi translation", null=True
            ),
        ),
    ]
